paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Los productos se han obtenido satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/products"
        "400":
          description: Los producctos no se han obtenido debido a un error

  /api/products/{uid}:
    get:
      summary: Obtiene un producto en particular por su Id
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          description: Id del producto
          schema:
            type: String
      responses:
        "200":
          description: El producto se ha encontrado correctamente
          content:
            application/json:
              schema:
                $ref: "#components/schemas/products"
        "500":
          description: Error de servidor

    put:
      summary: Actualiza el producto a partir de su Id
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          description: Id del producto que se desea Actualizar
          schema:
            type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
    post: 
       
      summary: Agrega un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/addProduct"
      responses:
        "201":
          description: Producto agregado exitosamente
        "400":
          description: Solicitud incorrecta

components:
  schemas:
    products:
      type: object
      properties:
        _id:
          type: String
          description: Id autogenerado por mongo
        title:
          type: String
          description: Nombre ded producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Codigo del producto
        category:
          type: String
          description: Categoria de los productos
        available:
          type: Boolean
          description: Si el producto esta disponible
        status: 
          type: Boolean
          description: El estado del producto
      example:
        _id: ObjectId("65f8d2449a1e1cbe4fd9e22a")
        title: Remera
        description: negro
        price: 50
        code: fesfgr
        status: true
        category: M


  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        code:
          type: String
          description: Codigo del producto
        status: 
          type: Boolean
          description: Estado del producto
        category: 
          type: String
          description: Categoria de los productos
        available: 
          type: Boolean
          description: Si el producto esta disponible
      example:
        title: Remera
        description: negro
        price: 50
        code: fesfgr
        status: true
        category: M
        available: true


  requestBodies:
     addProduct:
    type: object
    properties:
      title:
        type: string
        description: Nombre del producto
      description:
        type: string
        description: Descripción del producto
      price:
        type: number
        description: Precio del producto
      code:
        type: string
        description: Código del producto
      status: 
        type: boolean
        description: Estado del producto
      category: 
        type: string
        description: Categoría de los productos
      available: 
        type: boolean
        description: Si el producto está disponible
    example:
      title: Short
      description: Gris
      price: 50
      code: gegds
      status: true
      category: F
      available: true