openapi: '3.0.1'
info:
  title: 'Documentación API'
  description: 'Es una API de ropa'
  version: '1.0.0'
paths: 
  /api/carts:
    get:
      summary: Obtiene todos los carritos
      tags:
        - Carts
      responses:
        "200":
          description: Los productos se han obtenido satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/carts"
        "400":
          description: Los carritos no se han obtenido debido a un error

  /api/carts/{cid}:
    get:
      summary: Obtiene un carrito en particular por su Id
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: Id del carrito
          schema:
            type: string
      responses:
        "200":
          description: El carrito se ha encontrado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/carts"
        "500":
          description: Error de servidor
    put:
      summary: Actualiza el carrito a partir de su Id
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: Id del carrito que se desea actualizar
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/UpdateCartById"
      responses:
        "200":
          description: El carrito se ha actualizado correctamente
        "400":
          description: Error en la solicitud
        "500":
          description: Error de servidor

components:
  schemas:
    carts:
      type: object
      properties:
        product:
          type: string
          format: uuid
          description: ID del producto en el carrito
        quantity:
          type: integer
          description: Cantidad del producto en el carrito
  requestBodies:
    UpdateCartById:
      content:
        application/json:
          schema:
            type: object
            properties:
              product:
                type: string
                format: uuid
                description: ID del producto en el carrito
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
